Repository esx-framework/es_extended, pull requests merged in 2020-10, with the labels that each got.

#971 fix: Spanish translation
  locales/es.lua
Labels: hacktoberfest-accepted

#954 Update br.lua
  locales/br.lua
Labels: in-progress, waiting for update

#945 Feat(Rollup): Added watch: chokidar for hot reload stuff (Do not merge)
  src/ui/menu/rollup.config.js
Labels: in-progress
