Repository esx-framework/es_extended, pull requests merged in 2021-05, with the labels that each got.

#1147 feat(core/db): Changed to ghmattimysql.
  fxmanifest.lua
  modules/__base__/garages/server/events.lua
  modules/__base__/society/server/module.lua
  modules/__core__/cache/server/module.lua
  modules/__core__/character/server/events.lua
  modules/__core__/character/server/module.lua
  modules/__core__/datastore/server/module.lua
  modules/__core__/db/server/events.lua
  modules/__core__/db/server/module.lua
  modules/__core__/identity/server/events.lua
  modules/__core__/inventory/server/module.lua
  modules/__core__/migrate/server/module.lua
  modules/__core__/persistent/server/module.lua
  modules/__core__/skin/server/events.lua
  modules/__core__/skin/server/module.lua
Labels: do not merge, in-progress, reviewing

#1153 feat(core/status): Added status to identity + Optimizations
  config/default/config.status.lua
  modules/__core__/cache/server/module.lua
  modules/__core__/identity/client/module.lua
  modules/__core__/identity/server/module.lua
  modules/__core__/persistent/server/module.lua
  modules/__core__/status/client/events.lua
  modules/__core__/status/client/main.lua
  modules/__core__/status/client/module.lua
  modules/__core__/status/server/events.lua
  modules/__core__/status/server/main.lua
  modules/__core__/status/server/module.lua
Labels: do not merge, reviewing

#1148 tweak(client/functions): Updates to Events & Functions
  client/functions.lua
  client/main.lua
  version.json
Labels: do not merge, waiting for update

#1157 tweak(boot/discord): Add RPC action button
  boot/client/main.lua
Labels: enhancement, in-progress
